name: "CI checks"

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  commitlint:
    name: "Commit lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  check:
    name: "Code checks for typed_struct [OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Update rule:
          #   - latest Elixir on all supported OTP versions,
          #   - previous Elixir on the last two supported OTP versions,
          #   - oldest Elixir on the first and last supported OTP versions,
          #   - other Elixir version on the last supported OTP version.
          - elixir: "1.10"
            otp: "21.3"
          - elixir: "1.10"
            otp: "22.3"
          - elixir: "1.11"
            otp: "23.3"
          - elixir: "1.12"
            otp: "24.3"
          - elixir: "1.13"
            otp: "23.3"
          - elixir: "1.13"
            otp: "24.3"
          # - elixir: "1.14"
          #   otp: "23.3"
          # - elixir: "1.14"
          #   otp: "24.3"
          # - elixir: "1.14"
          #   otp: "25.0"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Elixir/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Fetch the dependencies
        run: mix deps.get
      - name: Check (mix check)
        run: mix check
